# Generated by Django 5.0.1 on 2024-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_processedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfiles',
            name='merge_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
