# Generated by Django 5.0.1 on 2024-01-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_processedfiles_merge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='column_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
